export const language = {

    fi: {
        // Onboarding (previous)
        skip: "Ohita",
        welcomeTo: "Tervetuloa",
        appName: "SISSI",
        description: "Seulontatyökalu instituutioille ja sidosryhmille",
        next: "Seuraava",

        // Role Selection
        chooseRoleTitle: "Valitse roolisi",
        chooseRoleSubtitle: "Valitse, miten haluat käyttää sovellusta",
        roleWorkerTitle: "Olen sijaistyöntekijä",
        roleWorkerSub: "Etsi töitä, hallitse vuoroja ja työllisty helposti.",
        roleInstTitle: "Olen instituutio",
        roleInstSub: "Ilmoita paikoista, hallitse työntekijöitä ja seuraa läsnäoloa.",

        // ... Login keys
        login: "Kirjaudu sisään",
        enterDetails: "Syötä sähköpostiosoitteesi ja salasanasi",
        email: "Sähköposti",
        password: "Salasana",
        forgotPassword: "Unohditko salasanasi?",
        noAccount: "Eikö sinulla ole tiliä? ",
        signUp: "Rekisteröidy",
        emailRequired: "Sähköposti on pakollinen.",
        invalidEmail: "Anna voimassa oleva sähköpostiosoite.",
        passwordRequired: "Salasana on pakollinen.",
        passwordLength: "Salasanan on oltava vähintään 6 merkkiä pitkä.",
        loginError: "Kirjautumisvirhe. Yritä uudelleen.",

        //forgot password
        passwordReset: "Salasanan palautus",
        emailResetPrompt: "Ole hyvä ja syötä sähköpostiosoitteesi palauttaaksesi salasanasi",
        emailPlaceholder: "Sähköposti",
        send: "Lähetä",
        back: "Takaisin",
        //otp
        checkMail: "Tarkista sähköpostisi",
        otpDescription: "Ole hyvä ja syötä 4-numeroinen koodi, joka lähetettiin osoitteeseen",
        submit: "Lähetä",
        invalidOtp: "Virheellinen koodi, yritä uudelleen.",
        otpError: "Syötä 4-numeroinen koodi",
        otpResendError: "Virhe koodin uudelleenlähetyksessä",
        //new password
        createNewPassword: "Luo uusi salasana",
        passwordDesc: "Uuden salasanasi on oltava eri kuin aiemmin käytetyt salasanat.",
        passwordLabel: "Salasana",
        confirmPasswordLabel: "Vahvista salasana",
        save: "Tallenna",
        passwordRequiredc: "Salasana vaaditaan.",
        confirmPasswordRequired: "Salasanan vahvistus vaaditaan.",
        passwordMinLength: "Salasanan on oltava vähintään 5 merkkiä.",
        passwordsDoNotMatch: "Salasanat eivät täsmää.",
        errorTitle: "Virhe",

        //register

        workerRegistration: "Työntekijän rekisteröityminen",
        institutionRegistration: "Laitoksen rekisteröityminen",
        fillDetails: "Täytä tietosi luodaksesi profiilin",
        fullName: "Koko nimi",
        institutionName: "Laitoksen nimi",
        unitName: "Yksikön nimi",
        unitManagerName: "Yksikön johtajan nimi",
        phoneNumber: "Puhelinnumero",
        confirmPassword: "Vahvista salasana",
        yearOfBirth: "Syntymävuosi",
        address: "Osoite",
        educationDetails: "Koulutustiedot",
        levelOfEducation: "Koulutustaso",
        degree: "Tutkinto",
        schoolName: "Koulun nimi",
        yearOfGraduation: "Valmistumisvuosi",
        criminalRecordLabel: "Minulla on voimassa oleva rikostaustaote lasten kanssa työskentelyyn",
        agreeToTerms: "Hyväksyn käyttöehdot",

        submitForApproval: "Lähetä hyväksyttäväksi",
        alreadyHaveAccount: "Onko sinulla jo tili? ",
        highSchool: "Lukio / Ammattikoulu",
        bachelor: "Kandidaatti",
        master: "Maisteri",
        phd: "Tohtori",
        emailReq: "Sähköposti vaaditaan.",
        emailInvalid: "Syötä voimassa oleva sähköpostiosoite.",
        mobileReq: "Puhelinnumero vaaditaan.",
        mobileInvalid: "Syötä voimassa oleva puhelinnumero (10-15 numeroa).",
        passReq: "Salasana vaaditaan.",
        passMin: "Salasanan on oltava vähintään 8 merkkiä.",
        passStrong: "Salasanan on sisällettävä iso ja pieni kirjain, numero sekä erikoismerkki.",
        confirmPassReq: "Vahvista salasana vaaditaan.",
        passMismatch: "Salasanat eivät täsmää.",
        nameReq: "Nimi vaaditaan.",
        nameInvalid: "Nimen tulee sisältää vain kirjaimia (2-50 merkkiä).",
        yearInvalid: "Syötä voimassa oleva vuosi (1900-2099).",
        ageError: "Sinun on oltava vähintään 18-vuotias.",
        yearBirthReq: "Syntymävuosi vaaditaan.",
        eduLevelReq: "Koulutustaso vaaditaan.",
        gradYearInvalid: "Syötä voimassa oleva valmistumisvuosi.",
        instReq: "Laitoksen nimi vaaditaan.",
        unitReq: "Yksikön nimi vaaditaan.",
        managerReq: "Johtajan nimi vaaditaan.",
        managerInvalid: "Syötä voimassa oleva nimi.",
        addressReq: "Osoite vaaditaan.",
        addressMin: "Osoitteen on oltava vähintään 10 merkkiä.",
        acceptTerms: "Hyväksy käyttöehdot jatkaaksesi.",
        signupFailed: "Rekisteröinti epäonnistui. Yritä uudelleen.",

        //dashboard user

        helloWelcome: "Hei, Tervetuloa 👋",
        browseShifts: "Selaa vuoroja",
        findAllAvailable: "Etsi kaikki vapaat vuorot",
        myShifts: "Minun vuoroni",
        upcomingCompleted: "Tulevat ja päättyneet",
        favoriteInstitutions: "Suosikkilaitokset",
        profilePreferences: "Profiili ja asetukset",
        //brouwes shift
        // browseShifts: "Selaa vuoroja",
        searchPlaceholder: "Hae nimellä, päivämäärällä, paikalla...",
        // institutionName: "Laitoksen nimi",
        // unitName: "Yksikön nimi",
        dateTime: "Päivämäärä ja kellonaika",
        location: "Sijainti",
        shortDescription: "Lyhyt kuvaus",
        badge: "Tila",
        available: "Vapaana",
        notAvailable: "Ei vapaana",
        favorite: "Suosikki",
        unfavorite: "Poista suosikki",
        bookNow: "Varaa nyt",
        searchNoResults: "Tuloksia ei löytynyt",
        createNew: 'Luo uusi vaihto',
        //shift

        shiftsHeader: "Työvuorot",
        tabInProgress: "Käynnissä",
        tabCompleted: "Valmiit",
        openChat: "Avaa keskustelu",
        statusComplete: "Valmis",
        statusPending: "Odottaa",
        searchPlace: 'Hae nimen, matkapuhelinnumeron, päivämäärän mukaan...',
        // Profile Screen
        profile: "Profiili",
        myProfile: "Oma profiili",
        favoriteInstitutions: "Suosikkilaitokset",
        notifications: "Ilmoitukset",
        aboutUs: "Tietoja meistä",
        privacyPolicy: "Tietosuojakäytäntö",
        logout: "Kirjaudu ulos",

        // Shift Details Screen
        shiftDetails: "Vuoron tiedot",
        institutionName: "Laitoksen nimi",
        unitName: "Yksikön nimi",
        dateTime: "Päivämäärä ja kellonaika",
        description: "Kuvaus",
        status: "Tila",

        // Tab Navigation
        home: "Koti",
        booking: "Varaus",
        inbox: "Saapuneet",

        // Institution Home Screen
        postedShifts: "Julkaistut vuorot",
        shiftBookingRequest: "Vuoron varausohjelma",
        bookedShifts: "Varatut vuorot",
        pastShifts: "Aiemmat vuorot",

        // Shift Booking Screen
        approve: "Hyväksy",
        approved: "Hyväksytty",
        decline: "Hylkää",
        shiftApprovedSuccessfully: "Vuoro hyväksytty onnistuneesti",
        workerHasBeenNotified: "Työntekijä on saanut ilmoituksen ja vuoro on vahvistettu.",
        shiftRequestDeclined: "Vuoropyyntö hylätty",
        workerWillSeeDeclineReason: "Työntekijä näkee hylkäämisen syyn ja voi hakea muita vuoroja.",
        done: "Valmis",
        search: "Etsi",
        searchByDateTime: "Etsi päivämäärän, ajan tai kuvauksen perusteella",

        // No content/empty states
        noContentAvailable: "Sisältöä ei ole saatavilla",
        noFavoritesFound: "Ei löytynyt suosikkilaitoksia",
        noResults: "Tuloksia ei löytynyt",
        // bookNow: "Varaa nyt",


        //logout
        logoutTitle: "Kirjaudu ulos",
        logoutMessage: "Oletko varma, että haluat kirjautua ulos?",
        yes: "Kyllä",
        no: "Ei",
        updateProfile: "Päivitä profiili",
        profileUpdated: "Profiili päivitetty onnistuneesti",

        //image picker modal
        chooseOption: "Valitse vaihtoehto",
        selectFromGallery: "Valitse galleriasta",
        takePhoto: "Ota kuva",
        cancel: "Peruuta",
        //notification setting

        generalNotification: "Yleiset ilmoitukset",
        sound: "Ääni",
        vibrate: "Värinä",
        newTipsAvailable: "Uusia vinkkejä saatavilla",
        // postedShifts: "Lähetetyt vuorot",
        //     searchPlaceholder: "Hae päivämäärällä, ajalla tai kuvauksella",
        //     description: "Kuvaus",
        // postedShifts: "Lähetetyt vuorot",
        // searchPlaceholder: "Hae päivämäärällä, ajalla tai kuvauksella",
        descriptionLabel: "Kuvaus",
        noBookings: "Ei vielä varauksia",
        remove: "Poista",
        edit: "Muokkaa",
        deleteRequestTitle: "Poista pyyntö",
        deleteRequestMessage: "Oletko varma, että haluat poistaa tämän pyynnön? Tätä toimintoa ei voi peruuttaa.",
        deleteBtn: "Poista",
        waiting: 'Odottaa hyväksyntää',
        viewDetail: 'Näytä tiedot',
        bookingSuccessful: "Varaus onnistui!",
    sessionConfirmed: "Istuntosi kohteen",
    withHasBeenConfirmed: "kanssa on vahvistettu",
    openChatWithInstitution: "Avaa keskustelu laitoksen kanssa",

    createNewShift: "Luo uusi työvuoro",
    editShift: "Muokkaa työvuoroa",
    selectDate: "Valitse päivämäärä",
    startTime: "Alkuaika",
    endTime: "Loppuaika",
    // location: "Sijainti",
    unit: "Yksikkö",
    // description: "Kuvaus",
    postShift: "Lähetä työvuoro",
    updateShift: "Päivitä työvuoro",
    updateSuccess: "Päivitetty onnistuneesti",
    postSuccess: "Lähetetty onnistuneesti",
    updateSub: "Työvuoro päivitetty onnistuneesti. Työntekijöille ilmoitettu.",
    postSub: "Työvuoro lähetetty onnistuneesti. Työntekijöille ilmoitettu automaattisesti.",
    
    // Validations
    valTitle: "Vahvistus",
    valDate: "Valitse päivämäärä",
    valStart: "Valitse alkuaika",
    valEnd: "Valitse loppuaika",
    valLoc: "Syötä sijainti",
    valUnit: "Syötä yksikkö",
    valDesc: "Syötä kuvaus",

    //

    typemsg:"Kirjoita viesti...",
    message:"Viesti",
    online:"verkossa"
    },


    en: {
    // Onboarding
    skip: "Skip",
    welcomeTo: "Welcome to",
    appName: "SISSI",
    description: "Screening tool for institutions and stakeholders",
    next: "Next",

    // Role Selection
    chooseRoleTitle: "Choose your role",
    chooseRoleSubtitle: "Select how you want to use the app",
    roleWorkerTitle: "I am a gig worker",
    roleWorkerSub: "Find jobs, manage shifts, and get employed easily.",
    roleInstTitle: "I am an institution",
    roleInstSub: "Post openings, manage workers, and track attendance.",

    // Login keys
    login: "Log In",
    enterDetails: "Enter your email and password",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    noAccount: "Don't have an account? ",
    signUp: "Sign Up",
    emailRequired: "Email is required.",
    invalidEmail: "Please enter a valid email address.",
    passwordRequired: "Password is required.",
    passwordLength: "Password must be at least 6 characters long.",
    loginError: "Login error. Please try again.",

    // Forgot password
    passwordReset: "Password Reset",
    emailResetPrompt: "Please enter your email to reset your password",
    emailPlaceholder: "Email",
    send: "Send",
    back: "Back",

    // OTP
    checkMail: "Check your email",
    otpDescription: "Please enter the 4-digit code sent to",
    submit: "Submit",
    invalidOtp: "Invalid code, please try again.",
    otpError: "Enter the 4-digit code",
    otpResendError: "Error resending code",

    // New password
    createNewPassword: "Create new password",
    passwordDesc: "Your new password must be different from previously used passwords.",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    save: "Save",
    passwordRequiredc: "Password is required.",
    confirmPasswordRequired: "Confirm password is required.",
    passwordMinLength: "Password must be at least 5 characters.",
    passwordsDoNotMatch: "Passwords do not match.",
    errorTitle: "Error",

    // Register
    workerRegistration: "Worker Registration",
    institutionRegistration: "Institution Registration",
    fillDetails: "Fill in your details to create a profile",
    fullName: "Full Name",
    institutionName: "Institution Name",
    unitName: "Unit Name",
    unitManagerName: "Unit Manager Name",
    phoneNumber: "Phone Number",
    confirmPassword: "Confirm Password",
    yearOfBirth: "Year of Birth",
    address: "Address",
    educationDetails: "Education Details",
    levelOfEducation: "Level of Education",
    degree: "Degree",
    schoolName: "School Name",
    yearOfGraduation: "Year of Graduation",
    criminalRecordLabel: "I have a valid criminal record extract for working with children",
    agreeToTerms: "I agree to the terms and conditions",

    submitForApproval: "Submit for Approval",
    alreadyHaveAccount: "Already have an account? ",
    highSchool: "High School / Vocational School",
    bachelor: "Bachelor",
    master: "Master",
    phd: "PhD",
    emailReq: "Email is required.",
    emailInvalid: "Enter a valid email address.",
    mobileReq: "Phone number is required.",
    mobileInvalid: "Enter a valid phone number (10-15 digits).",
    passReq: "Password is required.",
    passMin: "Password must be at least 8 characters.",
    passStrong: "Password must contain uppercase, lowercase, number, and special character.",
    confirmPassReq: "Confirm password is required.",
    passMismatch: "Passwords do not match.",
    nameReq: "Name is required.",
    nameInvalid: "Name should contain only letters (2-50 characters).",
    yearInvalid: "Enter a valid year (1900-2099).",
    ageError: "You must be at least 18 years old.",
    yearBirthReq: "Year of birth is required.",
    eduLevelReq: "Education level is required.",
    gradYearInvalid: "Enter a valid graduation year.",
    instReq: "Institution name is required.",
    unitReq: "Unit name is required.",
    managerReq: "Manager name is required.",
    managerInvalid: "Enter a valid name.",
    addressReq: "Address is required.",
    addressMin: "Address must be at least 10 characters.",
    acceptTerms: "Accept terms and conditions to continue.",
    signupFailed: "Registration failed. Please try again.",

    // Dashboard user
    helloWelcome: "Hello, Welcome 👋",
    browseShifts: "Browse Shifts",
    findAllAvailable: "Find all available shifts",
    myShifts: "My Shifts",
    upcomingCompleted: "Upcoming and Completed",
    favoriteInstitutions: "Favorite Institutions",
    profilePreferences: "Profile and Settings",

    // Browse shifts
    searchPlaceholder: "Search by name, date, location...",
    dateTime: "Date and Time",
    location: "Location",
    shortDescription: "Short description",
    badge: "Status",
    available: "Available",
    notAvailable: "Not Available",
    favorite: "Favorite",
    unfavorite: "Unfavorite",
    bookNow: "Book Now",
    searchNoResults: "No results found",
    createNew: 'Create New Shift',

    // Shifts
    shiftsHeader: "Shifts",
    tabInProgress: "In Progress",
    tabCompleted: "Completed",
    openChat: "Open Chat",
    statusComplete: "Complete",
    statusPending: "Pending",
    searchPlace: 'Search by name, phone, date...',

    // Profile Screen
    profile: "Profile",
    myProfile: "My Profile",
    notifications: "Notifications",
    aboutUs: "About Us",
    privacyPolicy: "Privacy Policy",
    logout: "Logout",

    // Shift Details Screen
    shiftDetails: "Shift Details",
    status: "Status",

    // Tab Navigation
    home: "Home",
    booking: "Booking",
    inbox: "Inbox",

    // Institution Home Screen
    postedShifts: "Posted Shifts",
    shiftBookingRequest: "Shift Booking Requests",
    bookedShifts: "Booked Shifts",
    pastShifts: "Past Shifts",

    // Shift Booking Screen
    approve: "Approve",
    approved: "Approved",
    decline: "Decline",
    shiftApprovedSuccessfully: "Shift approved successfully",
    workerHasBeenNotified: "The worker has been notified and the shift is confirmed.",
    shiftRequestDeclined: "Shift request declined",
    workerWillSeeDeclineReason: "The worker will see the decline reason and can apply for other shifts.",
    done: "Done",
    search: "Search",
    searchByDateTime: "Search by date, time or description",

    // No content/empty states
    noContentAvailable: "No content available",
    noFavoritesFound: "No favorite institutions found",
    noResults: "No results found",

    // Logout
    logoutTitle: "Log Out",
    logoutMessage: "Are you sure you want to log out?",
    yes: "Yes",
    no: "No",
    updateProfile: "Update Profile",
    profileUpdated: "Profile updated successfully",

    // Image picker modal
    chooseOption: "Choose an option",
    selectFromGallery: "Select from gallery",
    takePhoto: "Take a photo",
    cancel: "Cancel",

    // Notification setting
    generalNotification: "General Notifications",
    sound: "Sound",
    vibrate: "Vibrate",
    newTipsAvailable: "New tips available",
    descriptionLabel: "Description",
    noBookings: "No bookings yet",
    remove: "Remove",
    edit: "Edit",
    deleteRequestTitle: "Delete Request",
    deleteRequestMessage: "Are you sure you want to delete this request? This action cannot be undone.",
    deleteBtn: "Delete",
    waiting: 'Waiting for approval',
    viewDetail: 'View details',
    bookingSuccessful: "Booking successful!",
    sessionConfirmed: "Your session with",
    withHasBeenConfirmed: "has been confirmed",
    openChatWithInstitution: "Open chat with institution",

    createNewShift: "Create new shift",
    editShift: "Edit shift",
    selectDate: "Select date",
    startTime: "Start time",
    endTime: "End time",
    unit: "Unit",
    postShift: "Post shift",
    updateShift: "Update shift",
    updateSuccess: "Updated successfully",
    postSuccess: "Posted successfully",
    updateSub: "Shift updated successfully. Workers have been notified.",
    postSub: "Shift posted successfully. Workers notified automatically.",

    // Validations
    valTitle: "Validation",
    valDate: "Please select a date",
    valStart: "Please select a start time",
    valEnd: "Please select an end time",
    valLoc: "Please enter a location",
    valUnit: "Please enter a unit",
    valDesc: "Please enter a description",

    ///

    typemsg:"Type a message...",
    message:"Message",
    online:"Online"
}
}