export default {
  appLogo: require("./images/appLogo.png"),
  appLogo1: require("./images/loginTop.png"),
  bag: require("./images/bag.png"),
  review: require("./images/review.png"),

//   category1: require("./images/first.png"),
  splash: require("./images/splash.png"),
  emptyShift: require("./images/emptyShift.png"),
  first1: require("./images/first1.png"),
  bookedNow: require("./images/bookedNow.png"),
  Setting: require("./images/Setting.png"),
  Shiftbooking: require("./images/Shiftbooking.png"),
  Past: require("./images/Past.png"),
  Posted: require("./images/Posted.png"),
  ShiBookedftbooking: require("./images/Booked.png"),
  Inbox: require("./images/Inbox.png"),
  Notification2: require("./images/Notification2.png"),
  favort: require("./images/favort.png"),
  institute: require("./image/institute.jpg"),
  instituteType: require("./images/instituteType.png"),
  userType: require("./images/userType.png"),

  health: require("./images/health.png"),
  editp: require("./images/editp.png"),
  succesfuly: require("./images/succesfuly.png"),
  chatEmpty: require("./images/chatEmpty.png"),
  REMOVE: require("./images/REMOVE.png"),
  P1: require("./images/P1.png"),
  category5: require("./image/Services.png"),
  girlImg: require("./image/girlImage.png"),
  officeImg: require("./image/office.png"),
  locationCircle: require("./image/locationCircle.png"),
  location: require("./image/location.png"),
  msg: require("./image/msg.png"),
  heart: require("./image/heart.png"),
  home1: require("./images/home1.png"),
  yerar: require("./image/yerar.png"),
  bookingSuccess: require("./image/BookingSuccess.png"),
  call: require("./image/phone.png"),
  share: require("./image/share.png"),
  notification: require("./image/Notification.png"),
  notifcaton: require("./images/notifcaton.png"),
  privacy: require("./images/privacy.png"),
  banner1: require("./image/banner1.png"),
  mapbg: require("./image/mapbg.png"),
  rightBack: require("./images/rightBack.png"),
  mess1: require("./images/mess1.png"),
  chatMt: require("./images/chatMt.png"),
  logoutImg: require("./images/logoutImg.png"),

  Mobile: require("./images/Mobile.png"),
  marketplace: require("./images/marketplace.png"),
  CourierBoy: require("./images/CourierBoy.png"),
  // phonLogoapp: require('./images/Mobile.png'),
  Textphone: require("./images/Textphone.png"),
  Editpen: require("./images/Editpen.png"),
//   sp1: require("./images/sp1.png"),
  eoditphots: require("./images/eoditphots.png"),
  bagonboard: require("./images/bagonboard.png"),
  lock: require("./images/lock.png"),
  Textprofile: require("./images/Textprofile.png"),
  hide: require("./images/hide.png"),
  mess: require("./images/mess.png"),
  eye: require("./images/eye.png"),
  search1: require("./images/search1.png"),
  pin: require("./images/pin.png"),
  Phone1: require("./images/Phone1.png"),
  Iconreceiv: require("./images/Iconreceiv.png"),
  resetPassword: require("./images/resetpassword.png"),

  helpPrva: require("./images/helpPrva.png"),

  textLock: require("./images/textLock.png"),
  voies: require("./images/voies.png"),
  send: require("./images/send.png"),
  profiel: require("./images/profiel.png"),
  rightaArrow: require("./images/rightaArrow.png"),
  Addressicone: require("./images/Addressicone.png"),
  edit1: require("./images/edit1.png"),
  Next: require("./images/Next.png"),
  icons: require("./images/icons.png"),
  Vector: require("./images/Vector.png"),
  Notification: require("./images/Notification.png"),
//   trck: require("./images/trck.png"),
  Dots: require("./images/Dots.png"),
  arrowqdown: require("./images/arrowqdown.png"),
  Level: require("./images/Level.png"),
  more_vert: require("./images/more_vert.png"),
  Rectangle: require("./images/Rectangle.png"),

  black: require("./images/black.png"),
  location1: require("./images/location1.png"),
  
  right: require("./images/arrowRight.png"),
  Icon: require("./images/Icon.png"),
  google: require("./images/google.png"),
  Mesonmorpah: require("./images/Mesonmorpah.png"),
  MohronFag: require("./images/MohronFag.png"),
  prfile: require("./images/prfile.png"),
  pushup: require("./images/pushup.png"),
  running: require("./images/running.png"),
  back: require("./images/back.png"),
  cycling: require("./images/cycling.png"),
  arrowDown: require("./images/arrowDown.png"),
  logout: require("./images/logout.png"),
  Filter: require("./images/Filter.png"),
  dounArroww: require("./images/dounArroww.png"),
  aboutus: require("./images/aboutus.png"),
  BackLeft: require("./images/BackLeft.png"),
  userLogo: require("./images/userLogo.png"),
  calneder: require("./images/calneder.png"),
  calendarCircle: require("./images/calendarCircle.png"),
  time: require("./images/time.png"),
  pfioel12: require("./images/pfioel12.png"),
  Back1: require("./images/Back1.png"),
  salone: require("./images/salone.png"),
  man1: require("./images/man1.png"),
  no1: require("./images/no1.png"),
  post1: require("./images/post1.png"),
  arrowright1: require("./images/arrowright1.png"),
};
